version: "3"

services:

  api:
    build: 
      context: .
    image: "chsyu/apiserver:1.0"
    volumes:
      - .:/code
    container_name: api
    restart: always
    ports:
      - "5001:5000"
    networks:
      - local-net

networks:
  local-net:
